export const pathsAndText: { [key: string]: { textNeeded: boolean; logoPath: string } } = {
    '3ds': { logoPath: 'images/3ds.png', textNeeded: true },
    atari2600: { logoPath: 'images/atari2600.png', textNeeded: true },
    atari7800: { logoPath: 'images/atari7800.png', textNeeded: true },
    ds: { logoPath: 'images/ds.png', textNeeded: true },
    'nintendo ds': { logoPath: 'images/ds.png', textNeeded: true },
    'game boy advance': { logoPath: 'images/gbadvance.png', textNeeded: true },
    gb: { logoPath: 'images/gbclassic.png', textNeeded: false },
    'game boy': { logoPath: 'images/gbclassic.png', textNeeded: false },
    gbc: { logoPath: 'images/gbcolor.png', textNeeded: true },
    gcn: { logoPath: 'images/gcn.png', textNeeded: true },
    n64: { logoPath: 'images/n64.png', textNeeded: true },
    'nintendo 64': { logoPath: 'images/n64.png', textNeeded: true },
    nes: { logoPath: 'images/nes.png', textNeeded: true },
    pc: { logoPath: 'images/pc.svg', textNeeded: true },
    pcengine: { logoPath: 'images/pcengine.png', textNeeded: true },
    playstation: { logoPath: 'images/ps1.png', textNeeded: true },
    'playstation 2': { logoPath: 'images/ps2.png', textNeeded: true },
    'playstation 3': { logoPath: 'images/ps3.svg', textNeeded: true },
    'playstation 4': { logoPath: 'images/ps4.png', textNeeded: true },
    'playstation 5': { logoPath: 'images/ps5.png', textNeeded: true },
    psp: { logoPath: 'images/psp.png', textNeeded: true },
    psvita: { logoPath: 'images/psvita.png', textNeeded: true },
    segadreamcast: { logoPath: 'images/segadreamcast.png', textNeeded: true },
    segagamegear: { logoPath: 'images/segagamegear.png', textNeeded: true },
    segagenesis: { logoPath: 'images/segagenesis.png', textNeeded: true },
    segamastersystem: { logoPath: 'images/segamastersystem.png', textNeeded: true },
    segamegadrive: { logoPath: 'images/segamegadrive.png', textNeeded: true },
    segasaturn: { logoPath: 'images/segasaturn.png', textNeeded: true },
    snes: { logoPath: 'images/snes.png', textNeeded: true },
    switch: { logoPath: 'images/switch.svg', textNeeded: true },
    'switch 2': { logoPath: 'images/switch2.svg', textNeeded: true },
    wii: { logoPath: 'images/wii.png', textNeeded: false },
    'wii u': { logoPath: 'images/wiiu.png', textNeeded: false },
    xbox360: { logoPath: 'images/xbox360.png', textNeeded: true },
    xbox: { logoPath: 'images/xboxclassic.png', textNeeded: true },
    xboxone: { logoPath: 'images/xboxone.png', textNeeded: false },
    'xbox one': { logoPath: 'images/xboxone.png', textNeeded: false },
    zxspectrum: { logoPath: 'images/zxspectrum.png', textNeeded: true }
};
