/* prettier-ignore */
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Blurbs {
	charity: {
		text: string;
		enabled: boolean;
	}[];
	sponsor: {
		text: string;
		enabled: boolean;
	}[];
	bingothon: {
		text: string;
		enabled: boolean;
	}[];
}
